### PR TITLE
Update project for web deployment

### PR DESCRIPTION
**Pull request by pinguin999**
Hi @victoryang00 
I have "fixed" the web deploy for you.
It now can load the images, but it now crashes somewhere else.

Hope that helps you.

### CODE REVIEW

**Comment by vickiegpt** [comment]
Thanks a lot!

**Comment by vickiegpt** [comment]
image
Sounds like it crashed because of GL2's uninitialization.

**Comment by pinguin999** [comment]
Hi do you need more help with this?

**Comment by vickiegpt** [comment]
Yes, it would be much helpful to have help. I'm new to wasm Development and gl Deployment. We are working on a JIT RISC-V to WASM emulator. May be familiar with wasm afterwards.

**Comment by pinguin999** [comment]
I have opened a new PR with fixes for the web.

**Pull request merged**
